:toc2:
= AgnosticV Operator

AgnosticV is vars for link:https://github.com/redhat-cop/agnosticd[agnosticD].

This is the operator that takes care of updating the Catalog, based on several agnosticV repos.

The output of the operator, the final catalog, is composed of OpenShift resources:

* OpenShift Templates
* AnarchyGovernors


See also the link:https://github.com/redhat-cop/babylon[Babylon] Project.

== Structure of an agnosticv repo

----
common.yaml

ACCOUNT/
    account.yaml

   CATALOGITEM1/
         common.yaml
         dev.yaml
         test.yaml
         prod.yaml


   CATALOGITEM2/
         common.yaml
         dev.yaml
         test.yaml
         prod.yaml
----

.Example
----
common.yaml

gpte/
   account.yaml

   OCP4_CLUSTER/
         common.yaml
         dev.yaml
         test.yaml
         prod.yaml


   OCP_CLIENTVM/
         common.yaml
         dev.yaml
         test.yaml
         prod.yaml
----

In this example above, agnosticv-operator will produce 6 catalog items:

- gpte.ocp4-cluster.dev
- gpte.ocp4-cluster.test
- gpte.ocp4-cluster.prod
- gpte.ocp-clientvm.dev
- gpte.ocp-clientvm.test
- gpte.ocp-clientvm.prod

The files are merged in this order:

. common.yml
. ACCOUNT/account.yml
. ACCOUNT/CATALOG_ITEM/common.yml
. ACCOUNT/CATALOG_ITEM/STAGE.yml

for example:

. common.yml
. gpte/account.yml
. gpte/OCP4_CLUSTER/common.yml
. gpte/OCP4_CLUSTER/dev.yml

== Merging strategy


The merging strategy is:

- recursive
- lists are appended, not replaced


That means that if a list if defined in 2 files, then when it's merged, the lists are appended. For example:

[source,yaml]
.gpte/account.yaml
----
__meta__:
  secrets:
    - name: gpte-db
      namespace: gpte
      var: gpte_db
----

[source,yaml]
.gpte/CATALOGITEM/common.yaml
----
__meta__:
  secrets:
    - name: aws-gpte-prod
      namespace: gpte
----


Will produce:


[source,yaml]
----
__meta__:
  secrets:
    - name: gpte-db
      namespace: gpte
      var: gpte_db
    - name: aws-gpte-prod
      namespace: gpte
----

== Installation

=== Create the operator

This link:deploy-template.yaml[template] will take care of most of the things you need:

* serviceaccount/agnosticv-operator
* role.rbac.authorization.k8s.io/agnosticv-operator
* rolebinding.rbac.authorization.k8s.io/agnosticv-operator
* deployment.apps/agnosticv-operator
* clusterrole.authorization.openshift.io/agnosticv-operator
* clusterrolebinding.rbac.authorization.k8s.io/agnosticv-operator-clusterrolebinding
* customresourcedefinition.apiextensions.k8s.io/agnosticvrepos.gpte.redhat.com
* namespaces "agnosticv-operator"

Just run the following:

[source,shell]
----
oc process -f https://raw.githubusercontent.com/redhat-gpte-devopsautomation/agnosticv-operator/master/deploy-template.yaml|oc create -f -

----


=== Create agnosticV repos

The agnosticv-operator is listening on several agnosticV repos. This is represented by the Custom Resource `AgnosticVRepo`.

Here is an example for a private github repo.

.agnosticv-gpte-private-repo.yaml
[source,yaml]
----
apiVersion: gpte.redhat.com/v1
kind: AgnosticVRepo
metadata:
  generation: 1
  name: gpte-agnosticv
  namespace: "agnosticv-operator"
  selfLink: /apis/gpte.redhat.com/v1/namespaces/agnosticv-operator/agnosticvrepos/gpte-agnosticv
spec:
  ref: master
  sshKey: agnosticv-operator-sshkey
  url: git@github.com:redhat-gpe/agnosticv.git
  babylonAnarchyGovernorRepo: https://github.com/redhat-gpte-devopsautomation/babylon_anarchy_governor.git
  babylonAnarchyGovernorVersion: master
----

[source,shell]
----
oc create -f agnosticv-gpte-private-repo.yaml
----

If you repo is public, then you can use HTTP repo for `spec.url` and you don't need the following steps.

.Import the SSH private key needed to checkout the private repo
[source,shell]
----
oc create secret generic -n agnosticv-operator agnosticv-operator-sshkey --from-file=id_rsa=/home/ec2-user/.ssh/id_rsa
----

== Troubleshooting

.Look at the logs of the operator
----
[root@clientvm 0 ~]# oc project agnosticv-operator
[root@clientvm 0 ~]# oc get pods
NAME                                  READY   STATUS    RESTARTS   AGE
agnosticv-operator-7d6f867c56-jkwcn   2/2     Running   0          105s
[root@clientvm 0 ~]# oc logs -f agnosticv-operator-7d6f867c56-jkwcn -c ansible
----
